spring:
  cassandra:
    request:
      timeout: 10s
    connection:
      init-query-timeout: 10s
      connect-timeout: 10s
    keyspace-name: mynikeruns
    username:
    password:
    schema-action: create_if_not_exists
  data:
    mongodb:
      host:
      username:
      password:
      port:
      database: runningfiles
      uri: mongodb+srv://"+username+ ":"+password+"@cluster0.zh2tzbk.mongodb.net/?retryWrites=true&w=majority
datastax.astra:
  secure-connect-bundle: secure-connect-mynikeruns.zip
nikerun:
  defaultFile: /Volumes/MacProHD/intellijworkspaces/iAC-NikeRuns/iAC-NikeRuns/iAC-NikeRuns/activities-11.json
astra.db:
  id:
  region:
  keyspace:
  application.token:

